### ISSUE TITLE
Broken historic links

### ISSUE THREAD

**Issue by scotthooker** [jdaw1/placemat#99]
Great project - would it be beneficial to work out where the broken link to J R . c o m should be? 

<sup><sub>[Spaces inserted into link by jdaw1, 04 June 2021]</sub></sup>

**Comment by jdaw1** [comment]
Where is this link?

**Comment by scotthooker** [comment]
https://github.com/jdaw1/placemat/blob/530db52466dc2ee8b98453a6418b27c544c3db46/Pre_GitHub_docs/placemat.html#L1794

**Comment by scotthooker** [comment]
I can't honestly remember where I spotted it as this one is commented out. Pretty sure there was a couple of dead links though and was asking whether you wanted the correct new link or for me to put in a 301 for them.

No tease or anything meant! Was genuinely trying to be helpful... :(

**Comment by jdaw1** [comment]
Ahh. So JR.com didn’t mean [the defunct NYC electronics shop](https://en.wikipedia.org/wiki/J%26R) (which is why I thought it might refer to the antiquity of Postscript), it meant Jancis Robinson. That be *not-the-same-thing*.

The JancisRobinson.com forum needs a subscription. My subscription lapsed, so I don’t know whether current subscribers can see it.

The Pre_GitHub_docs had documentation in HTML. All of that was uploaded to the repo in case there was a failure of rewriting in markdown (and maybe as more general death-proofing). They are pre-GitGub docs, so not maintained. I’m not proficient at git: if non-maintainedness can be indicated somehow, please say how.

Would you object to my taking no action?

**Comment by jdaw1** [comment]
> Great project
Do you actually use it? If you do, please upload output to the web.

**Comment by scotthooker** [comment]
I'm one of the developers that works JR.com so I can find the correct link for you if needed

**Comment by jdaw1** [comment]
> I'm one of the developers that works JR.com so I can find the correct link for you if needed

That might be otherwise worth knowing (thank you), and tells me that your interest in the software was genuine (hurray!). But really I am not changing the pre-GitHub docs: they have been entirely replaced with the new markdown files.

**Comment by jdaw1** [comment]
There are several jancisrobinson.com links on ThePortForum.com ([list](http://www.theportforum.com/search.php?keywords=jancisrobinson.com)). I’d be willing to use admin powers to update any of those that have rotted.
